In [3]:
num=input("enter integer")
print(type(num))

enter integer5
<class 'str'>


In [4]:
for i in range(1,11):
  print(f'{num}x{i}={num *i}')

5x1=5
5x2=55
5x3=555
5x4=5555
5x5=55555
5x6=555555
5x7=5555555
5x8=55555555
5x9=555555555
5x10=5555555555


In [5]:
a=float(int(input("enter a number")))
b=float(int(input("enter a number")))
c=float(int(input("enter a number")))
print(f'addition:{a+b+c}')
print(f'subtraction:{a-b-c}')
print(f'multiplication:{a*b*c}')
print(f'division:{a/b/c}')

enter a number2
enter a number5
enter a number7
addition:14.0
subtraction:-10.0
multiplication:70.0
division:0.05714285714285715


In [6]:
numbers=[12,43,15,10,20]
tot=0
for i in numbers:
  tot+=i
  avg=tot/len(numbers)
  print(tot)
  print(avg)

12
2.4
55
11.0
70
14.0
80
16.0
100
20.0


In [7]:
import numpy as np

In [9]:
marks=np.array([34,65,87,12,54,76])
print("array:",marks)
print("type:" ,type(marks))

array: [34 65 87 12 54 76]
type: <class 'numpy.ndarray'>


In [11]:
a0d=np.array(40);
print(f'array: {a0d}')
print(f'shape: {a0d.shape}')
print(f'dimension: {a0d.ndim}')
print(f'size: {a0d.size}')
print(f'type: {a0d.dtype}')

array: 40
shape: ()
dimension: 0
size: 1
type: int64


In [12]:
a1d=np.array([1,2,3,4,5])
print(f'array: {a1d}')
print(f'shape: {a1d.shape}')
print(f'dimension: {a1d.ndim}')
print(f'size: {a1d.size}')
print(f'type: {a1d.dtype}')

array: [1 2 3 4 5]
shape: (5,)
dimension: 1
size: 5
type: int64


In [13]:
a2d=np.array([[1,2,3],[4,5,6]])
print(f'array: {a2d}')
print(f'shape: {a2d.shape}')
print(f'dimension: {a2d.ndim}')
print(f'size: {a2d.size}')
print(f'type: {a2d.dtype}')

array: [[1 2 3]
 [4 5 6]]
shape: (2, 3)
dimension: 2
size: 6
type: int64


In [14]:
a3d=np.array([[1,2,3],[7,8,9],[6,5,4],[3,9,2]])
print(f'array: {a3d}')
print(f'shape: {a3d.shape}')
print(f'dimension: {a3d.ndim}')
print(f'size: {a3d.size}')
print(f'type: {a3d.dtype}')
print(f'total size: {a3d.nbytes}')

array: [[1 2 3]
 [7 8 9]
 [6 5 4]
 [3 9 2]]
shape: (4, 3)
dimension: 2
size: 12
type: int64
total size: 96


In [15]:
print(a3d[0])
print(a3d[1])
print(a3d[2])
print(a3d[3])

[1 2 3]
[7 8 9]
[6 5 4]
[3 9 2]


In [16]:
print(f'Second row first element: {a3d[1,0]}')
print(f'Second row second element: {a3d[1,1]}')
print(f'Second row third element: {a3d[1,2]}')

Second row first element: 7
Second row second element: 8
Second row third element: 9


In [17]:
print(f'Second column first element: {a3d[0,1]}')
print(f'Second column second element: {a3d[1,1]}')
print(f'Second column third element: {a3d[2,1]}')

Second column first element: 2
Second column second element: 8
Second column third element: 5


In [18]:
print(f'row: {a3d[0,:]}')
print(f'row: {a3d[1,:]}')
print(f'row: {a3d[2,:]}')

row: [1 2 3]
row: [7 8 9]
row: [6 5 4]


In [19]:
marks1=np.array([34,65,87,12,54,76])
print(f'first four: {marks1[:4]}')
print(f'last two: {marks1[-2:]}')
print(f'every other: {marks1[::2]}')
print(f'reverse: {marks1[::-1]}')
print(f'reverse every other: {marks1[::-2]}')
print(f'alternate: {marks1[::2]}')

first four: [34 65 87 12]
last two: [54 76]
every other: [34 87 54]
reverse: [76 54 12 87 65 34]
reverse every other: [76 12 65]
alternate: [34 87 54]


In [20]:
full=np.full((2,3),7)
full

array([[7, 7, 7],
       [7, 7, 7]])

In [21]:
arr=np.ones(5,dtype=int)
arr

array([1, 1, 1, 1, 1])

arange() and linspace()

In [22]:
a=np.arange(0,10,2)
print(f'arange:{a}')
b=np.linspace(0,10,5)
print(f'linspace:{b}')
c=np.zeros(5)
print(f'zeros:{c}')
d=np.ones(5)
print(f'ones:{d}')

arange:[0 2 4 6 8]
linspace:[ 0.   2.5  5.   7.5 10. ]
zeros:[0. 0. 0. 0. 0.]
ones:[1. 1. 1. 1. 1.]


In [23]:
print(f'random decimal: {np.random.rand(5)}')

random decimal: [0.7403498  0.82357018 0.61913884 0.36135704 0.05826627]


In [24]:
print(f'random integer: {np.random.randint(100)}')


random integer: 28
